#Environment override
spring:
  datasource:
    username: mysqluser
    password: mysqlpw
    url: jdbc:mysql://mysql.default.svc.cluster.local/eventuate
eventuatelocal:
  cdc:
    db:
      user:
        name: root
      password: rootpassword
  kafka:
    bootstrap:
      servers: kafka.default.svc.cluster.local:9092
  zookeeper:
    connection:
      string: zookeeper.default.svc.cluster.local:2181