#Environment override
spring:
  datasource:
    username: mysqluser
    password: mysqlpw
    url: jdbc:mysql://mysql/eventuate
  cloud:
    config:
      uri: http://localhost:8888
eventuatelocal:
  cdc:
    db:
      user:
        name: root
      password: rootpassword
  kafka:
    bootstrap:
      servers: kafka:9092
  zookeeper:
    connection:
      string: zookeeper:2181